# The qa profile will use
# 1. localhost to connect to inventory service
# 2. Oracle database for storing data
spring:
  profiles: qa
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: IASON_TRADING_PARTNER
    password: IASON_TRADING_PARTNER
  jpa:
    hibernate:
      ddl-auto: none