# The qa profile will use
# 1. Oracle database for storing data
spring:
  profiles: qa
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: IASON_ACA_INTAKE
    password: IASON_ACA_INTAKE
  jpa:
    hibernate:
      ddl-auto: none